

DICCIONARIOS = {
    # 1. Estado civil
    "Marital status": {
        1: "Soltero",
        2: "Casado",
        3: "Viudo",
        4: "Divorciado",
        5: "Unión de hecho",
        6: "Separado legalmente"
    },
    
    # 2. Modo de aplicación
    "Application mode": {
        1: "1ª fase - contingente general",
        2: "Ordenanza Nº 612/93",
        5: "1ª fase - contingente especial (Islas Azores)",
        7: "Poseedores de otros cursos superiores",
        10: "Ordenanza Nº 854-B/99",
        15: "Estudiante internacional (licenciatura)",
        16: "1ª fase - contingente especial (Islas Madeira)",
        17: "2ª fase - contingente general",
        18: "3ª fase - contingente general",
        26: "Ordenanza Nº 533-A/99, apartado b2 (Plan Diferente)",
        27: "Ordenanza Nº 533-A/99, apartado b3 (Otra Institución)",
        39: "Mayores de 23 años",
        42: "Transferencia",
        43: "Cambio de curso",
        44: "Diplomados en especialización tecnológica",
        51: "Cambio de institución/curso",
        53: "Diplomados de ciclo corto",
        57: "Cambio de institución/curso (Internacional)"
    },
    
    # 3. Curso
    "Course": {
        33: "Tecnologías de Producción de Biocombustibles",
        171: "Diseño de Animación y Multimedia",
        8014: "Trabajo Social (asistencia nocturna)",
        9003: "Agronomía",
        9070: "Diseño de Comunicación",
        9085: "Enfermería Veterinaria",
        9119: "Ingeniería Informática",
        9130: "Equitación y Turismo",
        9147: "Gestión",
        9238: "Trabajo Social",
        9254: "Turismo",
        9500: "Enfermería",
        9556: "Higiene Oral",
        9670: "Gestión de Publicidad y Marketing",
        9773: "Periodismo y Comunicación",
        9853: "Educación Básica",
        9991: "Gestión (asistencia nocturna)"
    },
    
    # 4. Asistencia diurna/nocturna
    "Daytime/evening attendance": {
        1: "Diurna",
        0: "Nocturna"
    },
        # Becado
    "Scholarship holder": {
        1: "Sí",
        0: "No"
    },

    # Internacional
    "International": {
        1: "Sí",
        0: "No"
    },
    # 5. Calificación previa
    "Previous qualification": {
        1: "Educación secundaria",
        2: "Educación superior - licenciatura",
        3: "Educación superior - grado",
        4: "Educación superior - máster",
        5: "Educación superior - doctorado",
        6: "Estudiante en educación superior",
        9: "12º grado incompleto",
        10: "11º grado incompleto",
        12: "Otro - 11º grado",
        14: "10º grado completo",
        15: "10º grado incompleto",
        19: "Educación básica (9º/10º/11º grado) o equivalente",
        38: "Educación básica (6º/7º/8º grado) o equivalente",
        39: "Curso de especialización tecnológica",
        40: "Educación superior - grado (1º ciclo)",
        42: "Curso técnico profesional superior",
        43: "Educación superior - máster (2º ciclo)"
    },
    
    # 6. Nacionalidad
    "Nacionality": {
        1: "Portugués",
        2: "Alemán",
        6: "Español",
        11: "Italiano",
        13: "Holandés",
        14: "Inglés",
        17: "Lituano",
        21: "Angoleño",
        22: "Cabo Verdiano",
        24: "Guineano",
        25: "Mozambiqueño",
        26: "Santotomense",
        32: "Turco",
        41: "Brasileño",
        62: "Rumano",
        100: "Moldavo",
        101: "Mexicano",
        103: "Ucraniano",
        105: "Ruso",
        108: "Cubano",
        109: "Colombiano"
    },

    # Calificación de la Madre
    "Mother's qualification": {
        1: "Educación secundaria - 12º año o equivalente",
        2: "Educación superior - licenciatura",
        3: "Educación superior - grado",
        4: "Educación superior - máster",
        5: "Educación superior - doctorado",
        6: "Estudiante en educación superior",
        9: "12º año de escolaridad no completado",
        10: "11º año de escolaridad no completado",
        11: "7º año (anterior)",
        12: "Otro - 11º año de escolaridad",
        14: "10º año de escolaridad",
        18: "Curso de comercio general",
        19: "Educación básica 3er ciclo (9º/10º/11º año) o equivalente",
        22: "Curso técnico-profesional",
        26: "7º año de escolaridad",
        27: "2º ciclo del curso general de secundaria",
        29: "9º año de escolaridad no completado",
        30: "8º año de escolaridad",
        34: "Desconocido",
        35: "No sabe leer ni escribir",
        36: "Sabe leer sin tener un 4º año de escolaridad",
        37: "Educación básica 1er ciclo (4º/5º año) o equivalente",
        38: "Educación básica 2º ciclo (6º/7º/8º año) o equivalente",
        39: "Curso de especialización tecnológica",
        40: "Educación superior - grado (1º ciclo)",
        41: "Curso de estudios superiores especializados",
        42: "Curso técnico-profesional superior",
        43: "Educación superior - máster (2º ciclo)",
        44: "Educación superior - doctorado (3er ciclo)"
    },
        # Calificación del Padre
    "Father's qualification": {
        1: "Educación secundaria - 12º año o equivalente",
        2: "Educación superior - licenciatura",
        3: "Educación superior - grado",
        4: "Educación superior - máster",
        5: "Educación superior - doctorado",
        6: "Estudiante en educación superior",
        9: "12º año de escolaridad no completado",
        10: "11º año de escolaridad no completado",
        11: "7º año (anterior)",
        12: "Otro - 11º año de escolaridad",
        13: "Curso complementario de secundaria (2º año)",
        14: "10º año de escolaridad",
        18: "Curso de comercio general",
        19: "Educación básica 3er ciclo (9º/10º/11º año) o equivalente",
        20: "Curso complementario de secundaria",
        22: "Curso técnico-profesional",
        25: "Curso complementario de secundaria no completado",
        26: "7º año de escolaridad",
        27: "2º ciclo del curso general de secundaria",
        29: "9º año de escolaridad no completado",
        30: "8º año de escolaridad",
        31: "Curso general de administración y comercio",
        33: "Contabilidad y administración complementaria",
        34: "Desconocido",
        35: "No sabe leer ni escribir",
        36: "Sabe leer sin tener un 4º año de escolaridad",
        37: "Educación básica 1er ciclo (4º/5º año) o equivalente",
        38: "Educación básica 2º ciclo (6º/7º/8º año) o equivalente",
        39: "Curso de especialización tecnológica",
        40: "Educación superior - grado (1º ciclo)",
        41: "Curso de estudios superiores especializados",
        42: "Curso técnico-profesional superior",
        43: "Educación superior - máster (2º ciclo)",
        44: "Educación superior - doctorado (3er ciclo)"
    },
        "Mother's occupation": {
        0: "Estudiante",
        1: "Representantes del poder legislativo y ejecutivo, directores y gerentes",
        2: "Especialistas en actividades intelectuales y científicas",
        3: "Técnicos y profesionales de nivel intermedio",
        4: "Personal administrativo",
        5: "Trabajadores en servicios personales, seguridad y comercio",
        6: "Agricultores y trabajadores calificados en agricultura, pesca y silvicultura",
        7: "Trabajadores calificados en industria, construcción y artesanos",
        8: "Operadores de instalaciones y maquinaria y ensambladores",
        9: "Trabajadores no calificados",
        10: "Profesiones en las fuerzas armadas",
        90: "Otra situación",
        99: "(Vacío)",
        122: "Profesionales de la salud",
        123: "Docentes",
        125: "Especialistas en tecnologías de la información y comunicación (TIC)",
        131: "Técnicos y profesionales de nivel intermedio en ciencias e ingeniería",
        132: "Técnicos y profesionales de nivel intermedio en salud",
        134: "Técnicos de nivel intermedio en servicios legales, sociales, culturales, deportivos y similares",
        141: "Trabajadores de oficina, secretarios y operadores de procesamiento de datos",
        143: "Operadores de datos, contabilidad, servicios estadísticos, financieros y registros",
        144: "Otro personal de apoyo administrativo",
        151: "Trabajadores de servicios personales",
        152: "Vendedores",
        153: "Trabajadores de cuidados personales y similares",
        171: "Trabajadores calificados en construcción y similares, excepto electricistas",
        173: "Trabajadores calificados en impresión, fabricación de instrumentos de precisión, joyeros, artesanos y similares",
        175: "Trabajadores en procesamiento de alimentos, carpintería, confección y otras industrias y artesanías",
        191: "Trabajadores de limpieza",
        192: "Trabajadores no calificados en agricultura, producción animal, pesca y silvicultura",
        193: "Trabajadores no calificados en la industria extractiva, construcción, manufactura y transporte",
        194: "Ayudantes de preparación de comidas"
    },
        "Father's occupation": {
        0: "Estudiante",
        1: "Representantes del poder legislativo y ejecutivo, directores y gerentes",
        2: "Especialistas en actividades intelectuales y científicas",
        3: "Técnicos y profesionales de nivel intermedio",
        4: "Personal administrativo",
        5: "Trabajadores en servicios personales, seguridad y comercio",
        6: "Agricultores y trabajadores calificados en agricultura, pesca y silvicultura",
        7: "Trabajadores calificados en industria, construcción y artesanos",
        8: "Operadores de instalaciones y maquinaria y ensambladores",
        9: "Trabajadores no calificados",
        10: "Profesiones en las fuerzas armadas",
        90: "Otra situación",
        99: "(Vacío)",
        101: "Oficiales de las fuerzas armadas",
        102: "Sargentos de las fuerzas armadas",
        103: "Otro personal de las fuerzas armadas",
        112: "Directores de servicios administrativos y comerciales",
        114: "Directores de hotelería, restauración, comercio y otros servicios",
        121: "Especialistas en ciencias físicas, matemáticas, ingeniería y técnicas relacionadas",
        122: "Profesionales de la salud",
        123: "Docentes",
        124: "Especialistas en finanzas, contabilidad, organización administrativa, relaciones públicas y comerciales",
        131: "Técnicos y profesionales de nivel intermedio en ciencias e ingeniería",
        132: "Técnicos y profesionales de nivel intermedio en salud",
        134: "Técnicos de nivel intermedio en servicios legales, sociales, culturales, deportivos y similares",
        135: "Técnicos en tecnologías de la información y comunicación (TIC)",
        141: "Trabajadores de oficina, secretarios y operadores de procesamiento de datos",
        143: "Operadores de datos, contabilidad, servicios estadísticos, financieros y registros",
        144: "Otro personal de apoyo administrativo",
        151: "Trabajadores de servicios personales",
        152: "Vendedores",
        153: "Trabajadores de cuidados personales y similares",
        154: "Personal de servicios de protección y seguridad",
        161: "Agricultores orientados al mercado y trabajadores calificados en producción animal",
        163: "Agricultores, ganaderos, pescadores, cazadores y recolectores de subsistencia",
        171: "Trabajadores calificados en construcción y similares, excepto electricistas",
        172: "Trabajadores calificados en metalurgia, metalistería y similares",
        174: "Trabajadores calificados en electricidad y electrónica",
        175: "Trabajadores en procesamiento de alimentos, carpintería, confección y otras industrias y artesanías",
        181: "Operadores de instalaciones fijas y maquinaria",
        182: "Trabajadores ensambladores",
        183: "Conductores de vehículos y operadores de equipos móviles",
        192: "Trabajadores no calificados en agricultura, producción animal, pesca y silvicultura",
        193: "Trabajadores no calificados en la industria extractiva, construcción, manufactura y transporte",
        194: "Ayudantes de preparación de comidas",
        195: "Vendedores ambulantes (excepto alimentos) y prestadores de servicios callejeros"
    },

    # 7. Género
    "Gender": {
        1: "Masculino",
        0: "Femenino"
    },
    
    # 8. Resultado final
    "Target": {
        "dropout": "Desertor",
        "enrolled": "Inscrito",
        "graduate": "Graduado"
    },
    
    # 9. Variables binarias
    "Displaced": {0: "No", 1: "Sí"},
    "Educational special needs": {0: "No", 1: "Sí"},
    "Debtor": {0: "No", 1: "Sí"},
    "Tuition fees up to date": {0: "No", 1: "Sí"}
}
